[package]
name = "fansland-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name ="api"
path ="src/api/cmd/main.rs"

[[bin]]
name ="client"
path ="src//cmd/main.rs"