version: "3.9"

services:
  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/postgresql:/var/lib/postgresql/data
  #   restart: no #跟随docker的启动而启动
  #   environment:
  #     - POSTGRES_PASSWORD=Qss2024postgG
  #     - POSTGRES_USER=testuser
  #     - POSTGRES_DB=fansland
  redis: #redis服务/其他服务（web服务/nginx服务等）
    image: redis:7 #redis镜像，如果镜像容器没有会去自动拉取
    # container_name: redis #设置容器名称
    command: redis-server --appendonly yes --requirepass 'gooDluck4u' #开启持久化的支持并设置认证密码
    restart: always #跟随docker的启动而启动
    volumes:
      - ./data/redis:/data #数据文件挂载
    ports:
      - 6379:6379
