version: "3.9"

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: mysql-fansland
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
      # root 密码 - root password
      MYSQL_USER: root
      MYSQL_DATABASE: fansland_sol
      MYSQL_ROOT_HOST: '%'
      # MYSQL_ROOT_HOST: '172.20.0.1'
      MYSQL_ROOT_PASSWORD: ae633jmFLiAGqigSO41
    ports:
      - 3306:3306
    volumes:
      # 数据挂载 - Data mounting
      - ./data/mysql/data:/var/lib/mysql
      # - ./fansland1.0.sql:/docker-entrypoint-initdb.d/init.sql
      # 日志
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      # Modify the Mysql 8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    # networks:
      # - uuunet
  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/postgresql:/var/lib/postgresql/data
    restart: always #跟随docker的启动而启动
  #   environment:
  #     - POSTGRES_PASSWORD=Qss2024postgG
  #     - POSTGRES_USER=testuser
  #     - POSTGRES_DB=fansland
  redis: #redis服务/其他服务（web服务/nginx服务等）
    image: redis:7 #redis镜像，如果镜像容器没有会去自动拉取
    # container_name: redis #设置容器名称
    command: redis-server --appendonly yes --requirepass 'gooDluck4u' #开启持久化的支持并设置认证密码
    restart: always #跟随docker的启动而启动
    volumes:
      - ./data/redis:/data #数据文件挂载
    ports:
      - 6379:6379
